Feature/produce nuget for fs sonar runner core
jmecosta/sonar-fsharp-plugin pull request #101
Opened 2020-06-30 14:05 UTC by jmecosta

#75 update linter on sonar extensions

2020-06-30 14:40 UTC, milbrandt commented
You need this as a nuget in some other place? Should this be permanently generated or only for working? If permanently I would propose to add it to the release notes.
Maybe we should make a minor release 3.1.1 anyway now that the deprecated api is removed.

2020-06-30 14:47 UTC, jmecosta commented
Yeah, im kind of copy pasting the code on the visual studio extension, so
its best just to reuse this.



On Tue, 30 Jun 2020, 17:40 Volker Milbrandt, <notifications@github.com>
wrote:

> You need this as a nuget in some other place? Should this be permanently
> generated or only for working? If permanently I would propose to add it to
> the release notes.
> Maybe we should make a minor release 3.1.1 anyway now that the deprecated
> api is removed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#issuecomment-651837474>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH6HSEQGPICZASRINW5HS3RZH2PRANCNFSM4OMIVKLQ>
> .
>

2020-06-30 14:48 UTC, milbrandt commented on appveyor.yml
> +  assembly_version: '{version}.0'
shouldn't we change the version in line 8 accordingly and from here keep only reference?

2020-06-30 14:50 UTC, jmecosta commented
Basically because we dont know if this number upgrades has changes on the
f# side i would rather have it created all the time.

On Tue, 30 Jun 2020, 17:48 Jorge Costa, <jmecosta@gmail.com> wrote:

> Yeah, im kind of copy pasting the code on the visual studio extension, so
> its best just to reuse this.
>
>
>
> On Tue, 30 Jun 2020, 17:40 Volker Milbrandt, <notifications@github.com>
> wrote:
>
>> You need this as a nuget in some other place? Should this be permanently
>> generated or only for working? If permanently I would propose to add it to
>> the release notes.
>> Maybe we should make a minor release 3.1.1 anyway now that the deprecated
>> api is removed.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#issuecomment-651837474>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAH6HSEQGPICZASRINW5HS3RZH2PRANCNFSM4OMIVKLQ>
>> .
>>
>

2020-06-30 14:55 UTC, jmecosta commented
I wouldnt mind, but then everything needs to be major.minor.buildnumber



On Tue, 30 Jun 2020, 17:48 Volker Milbrandt, <notifications@github.com>
wrote:

> *@milbrandt* commented on this pull request.
> ------------------------------
>
> In appveyor.yml
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#discussion_r447743304>
> :
>
> > @@ -30,9 +30,9 @@ dotnet_csproj:
>    file: '**\*.csproj;**\*.props;**\*.fsproj;**\*.xml'
>    version: '{version}'
>    package_version: '{version}'
> -  assembly_version: '{version}'
> -  file_version: '{version}'
> -  informational_version: '{version}'
> +  assembly_version: '{version}.0'
>
> shouldn't we change the version in line 8 accordingly and from here keep
> only reference?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#pullrequestreview-440094241>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH6HSAMIUSPZWY44GDL6H3RZH3MZANCNFSM4OMIVKLQ>
> .
>

2020-06-30 15:02 UTC, milbrandt commented
> I wouldnt mind, but then everything needs to be major.minor.buildnumber

You wanted to reference on my review comment above? My proposal was be to define in line 8:

    version: 3.1.{build}.0

and then revert

    assembly_version: '{version}'
    file_version: '{version}'	
    informational_version: '{version}'

If ommitting the last `.0` helps, it's fine for me. 

I would prefer if all version stings are identical - so there can't be any misconceptions in case of bugs.

2020-06-30 16:54 UTC, jmecosta commented
Yep, the last 0 then needs to go.

On Tue, 30 Jun 2020, 18:03 Volker Milbrandt, <notifications@github.com>
wrote:

> I wouldnt mind, but then everything needs to be major.minor.buildnumber
>
> You wanted to reference on my review comment above? My proposal was be to
> define in line 8:
>
> version: 3.1.{build}.0
>
> and then revert
>
> assembly_version: '{version}'
> file_version: '{version}'	
> informational_version: '{version}'
>
> If ommitting the last .0 helps, it's fine for me.
>
> I would prefer if all version stings are identical - so there can't be any
> misconceptions in case of bugs.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#issuecomment-651851961>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH6HSAM2T52YW5GQD7SLOTRZH5C5ANCNFSM4OMIVKLQ>
> .
>

2020-06-30 19:06 UTC, milbrandt commented on appveyor.yml
> +  assembly_version: '{version}.0'
Thanks for fixing it

2020-06-30 19:17 UTC, milbrandt requested changes
Please add some hint to the [RELEASE_NOTES.md](https://github.com/jmecsoftware/sonar-fsharp-plugin/blob/master/RELEASE_NOTES.md) that plugin versioning changed.

2020-06-30 19:18 UTC, milbrandt commented on appveyor.yml
> +version: 3.1.{build}
What is now displayed in the SonarQube Server Marketplace as version? Until now it was e.g. `3.1 (build 345)installed`

2020-06-30 20:10 UTC, jmecosta commented
i think its more accurate since the version is 3.1.0.345 -> goes to  3.1
(build 345)
as 1.5.7 -> 1.5.7installed

but as far as i can see, i can find 3 types of verison

1. 1.1
2. 1.1.1
3. 1.3 (build x)
4. 1.4.3 (build x)



On Tue, Jun 30, 2020 at 10:18 PM Volker Milbrandt <notifications@github.com>
wrote:

> *@milbrandt* commented on this pull request.
> ------------------------------
>
> In appveyor.yml
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#discussion_r447922672>
> :
>
> > @@ -5,7 +5,7 @@
>  #---------------------------------#
>
>  # version format
> -version: 3.1.0.{build}
> +version: 3.1.{build}
>
> What is now displayed in the SonarQube Server Marketplace as version?
> Until now it was e.g. 3.1 (build 345)installed
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#pullrequestreview-440314850>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH6HSAS34OLHIL4NRUFP3TRZI3BRANCNFSM4OMIVKLQ>
> .
>

2020-07-14 08:32 UTC, milbrandt approved these changes

2020-07-14 08:33 UTC, milbrandt commented
> Please add some hint to the [RELEASE_NOTES.md](https://github.com/jmecsoftware/sonar-fsharp-plugin/blob/master/RELEASE_NOTES.md) that plugin versioning changed.

I added now myself some release notes draft

2020-07-14 09:21 UTC, jmecosta commented
Miss this one

On Tue, 14 Jul 2020, 11:34 Volker Milbrandt, <notifications@github.com>
wrote:

> Assigned #101
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101> to
> @jmecosta <https://github.com/jmecosta>.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#event-3543095189>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH6HSH25EUBHKNIHFJP46DR3QKAVANCNFSM4OMIVKLQ>
> .
>

2020-07-20 16:17 UTC, milbrandt commented
> Miss this one

@jmecosta you will continue this PR? 
Do you intend to publish the new package to nuget.org? 
Shall we release a version because of the changed versioning scheme as soon as the PR is merged?

2020-07-20 16:42 UTC, jmecosta commented
Yep, i will take care of it later today

On Mon, 20 Jul 2020, 19:17 Volker Milbrandt, <notifications@github.com>
wrote:

> Miss this one
>
> @jmecosta <https://github.com/jmecosta> you will continue this PR?
> Do you intend to publish the new package to nuget.org?
> Shall we release a version because of the changed versioning scheme as
> soon as the PR is merged?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#issuecomment-661145603>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH6HSB56JTRPTDOGQBSBJDR4RUZ5ANCNFSM4OMIVKLQ>
> .
>

2020-07-20 19:43 UTC, jmecosta commented
@milbrandt since there are not functional changes i think we can skip this change and just release when we have more stuff coming in

2020-07-20 19:45 UTC, merged

2020-07-20 19:57 UTC, jmecosta commented
nuget published https://www.nuget.org/packages/FsSonarRunnerCore/3.1.382

2020-07-20 20:15 UTC, milbrandt commented
> @milbrandt since there are not functional changes i think we can skip this change and just release when we have more stuff coming in

@jmecosta you're right that this PR didn't change functionality. 
But since 3.1.0 in March there were several changes. And SonarQube wants an release at least every 6 month. All togerther I think we could  do a service release 3.1.382 to have the same versioning scheme for the released plugin as for nuget.
Publishing to nuget.org is not automated in the yaml pipeline as far as I saw?

2020-07-21 08:09 UTC, jmecosta commented
Ok lets than do the release. I will check the auto deploy of nuget

On Mon, 20 Jul 2020, 23:15 Volker Milbrandt, <notifications@github.com>
wrote:

> @milbrandt <https://github.com/milbrandt> since there are not functional
> changes i think we can skip this change and just release when we have more
> stuff coming in
>
> @jmecosta <https://github.com/jmecosta> you're right that this PR didn't
> change functionality.
> But since 3.1.0 in March there were several changes. And SonarQube wants
> an release at least every 6 month. All togerther I think we could do a
> service release 3.1.382 to have the same versioning scheme for the released
> plugin as for nuget.
> Publishing to nuget.org is not automated in the yaml pipeline as far as I
> saw?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jmecsoftware/sonar-fsharp-plugin/pull/101#issuecomment-661309808>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH6HSDUTHI3NHYL2Y6L2O3R4SQVPANCNFSM4OMIVKLQ>
> .
>

2020-07-21 08:40 UTC, jmecosta commented
@milbrandt should all be done now, 3.1.384 is now the only version in every place

2020-07-21 16:55 UTC, milbrandt commented
👍